export const BASE_URL = "https://kairoscope-backend.glitch.me", //Development server
             //BASE_URL = "", //Production server
             API_BASE_URL = `${BASE_URL}/api/v1`,
             API_FACEBOOK_LOGIN = `${BASE_URL}/auth/facebook`,
             API_JWTMESSAGE_VERIFY = `${API_BASE_URL}/jwtMessageVerify`,
             API_USERNAME_PASSWORD_LOGIN = `${API_BASE_URL}/auth/usernamePasswordLogin`,
             API_CHECK_USERNAME_AVAILABLE = `${API_BASE_URL}/auth/checkUsernameAvailable`,
             API_REGISTER_NEW_USER = `${API_BASE_URL}/auth/registerNewUser`,
             API_FETCH_READINGS = `${API_BASE_URL}/fetchReadings`,
             API_FETCH_READINGS_BASEON_HEXAGRAM = `${API_BASE_URL}/fetchReadingsBaseOnHexagram`,
             API_FETCH_HEXAGRAMS = `${API_BASE_URL}/fetchHexagrams`,
             API_SEARCH_READINGS = `${API_BASE_URL}/searchReadings`;
