export const JWT_MESSAGE = 'KairoScope_JWT';
export const ADMINISTRATOR_ROLE = 1;
// export const BASE_URL = 'https://kairoscope-backend.glitch.me'; // Development server
// export const BASE_URL = 'http://localhost:8080'; // Development server
export const BASE_URL = 'https://kairoscope.resonancepath.com:8080'; // Production server
export const AWS_READING_URL = 'https://b8bpiar0bh.execute-api.us-west-2.amazonaws.com/dev';
export const AWS_JOURNAL_URL = 'https://xbfdcju8sf.execute-api.us-west-2.amazonaws.com/dev';
export const AWS_HEXAGRAM_URL = 'https://3i0e59njre.execute-api.us-west-2.amazonaws.com/dev';
export const AWS_USER_URL = 'https://9p4s43slt2.execute-api.us-west-2.amazonaws.com/dev';
export const NUMBER_OF_READING_PER_PAGE_RECENT_READINGS = 5; // How many reading will show on the recent readings page.
export const NUMBER_OF_USER_PER_PAGE = 30; // How many user will be showed in the all user list.
export const NUMBER_OF_READING_PER_PAGE = 10; // How many reading will be showed in one page.
export const NUMBER_PER_PAGE_JOURNAL = 5; // How many journal will be showed in all journal page.
export const CLOUDINARY_UPLOAD_PRESET = 'KairoScopeWebApp'; // The preset of Cloudinary.
export const TOTAL_NUMBER_HEXAGRAM = 64; // The total amount Hexagram.
